# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-22 12:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imageeditor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='editedphotos/')),
                ('effect', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imageeditor.Photo')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
